//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.SLProductVariation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductVariationInfo", Namespace="http://schemas.datacontract.org/2004/07/DomainModel")]
    [System.SerializableAttribute()]
    public partial class ProductVariationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char conditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_brand_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_color_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_cutting_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_type_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_variation_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char condition {
            get {
                return this.conditionField;
            }
            set {
                if ((this.conditionField.Equals(value) != true)) {
                    this.conditionField = value;
                    this.RaisePropertyChanged("condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_brand_id {
            get {
                return this.product_brand_idField;
            }
            set {
                if ((this.product_brand_idField.Equals(value) != true)) {
                    this.product_brand_idField = value;
                    this.RaisePropertyChanged("product_brand_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_color_id {
            get {
                return this.product_color_idField;
            }
            set {
                if ((this.product_color_idField.Equals(value) != true)) {
                    this.product_color_idField = value;
                    this.RaisePropertyChanged("product_color_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_cutting_id {
            get {
                return this.product_cutting_idField;
            }
            set {
                if ((this.product_cutting_idField.Equals(value) != true)) {
                    this.product_cutting_idField = value;
                    this.RaisePropertyChanged("product_cutting_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_type_id {
            get {
                return this.product_type_idField;
            }
            set {
                if ((this.product_type_idField.Equals(value) != true)) {
                    this.product_type_idField = value;
                    this.RaisePropertyChanged("product_type_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_variation_id {
            get {
                return this.product_variation_idField;
            }
            set {
                if ((this.product_variation_idField.Equals(value) != true)) {
                    this.product_variation_idField = value;
                    this.RaisePropertyChanged("product_variation_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char sex {
            get {
                return this.sexField;
            }
            set {
                if ((this.sexField.Equals(value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLProductVariation.ISLProductVariation")]
    public interface ISLProductVariation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/ReadPV", ReplyAction="http://tempuri.org/ISLProductVariation/ReadPVResponse")]
        MVC3.SLProductVariation.ProductVariationInfo ReadPV(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/CreatePV", ReplyAction="http://tempuri.org/ISLProductVariation/CreatePVResponse")]
        int CreatePV(MVC3.SLProductVariation.ProductVariationInfo ProductVariation, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/UpdatePV", ReplyAction="http://tempuri.org/ISLProductVariation/UpdatePVResponse")]
        int UpdatePV(MVC3.SLProductVariation.ProductVariationInfo ProductVariation, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/DeletePV", ReplyAction="http://tempuri.org/ISLProductVariation/DeletePVResponse")]
        int DeletePV(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/ReadAllPV", ReplyAction="http://tempuri.org/ISLProductVariation/ReadAllPVResponse")]
        MVC3.SLProductVariation.ProductVariationInfo[] ReadAllPV(ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductVariation/ReadAllPVCondition", ReplyAction="http://tempuri.org/ISLProductVariation/ReadAllPVConditionResponse")]
        MVC3.SLProductVariation.ProductVariationInfo[] ReadAllPVCondition(char status, ref string[] errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLProductVariationChannel : MVC3.SLProductVariation.ISLProductVariation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLProductVariationClient : System.ServiceModel.ClientBase<MVC3.SLProductVariation.ISLProductVariation>, MVC3.SLProductVariation.ISLProductVariation {
        
        public SLProductVariationClient() {
        }
        
        public SLProductVariationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLProductVariationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLProductVariationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLProductVariationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC3.SLProductVariation.ProductVariationInfo ReadPV(int id, ref string[] errors) {
            return base.Channel.ReadPV(id, ref errors);
        }
        
        public int CreatePV(MVC3.SLProductVariation.ProductVariationInfo ProductVariation, ref string[] errors) {
            return base.Channel.CreatePV(ProductVariation, ref errors);
        }
        
        public int UpdatePV(MVC3.SLProductVariation.ProductVariationInfo ProductVariation, ref string[] errors) {
            return base.Channel.UpdatePV(ProductVariation, ref errors);
        }
        
        public int DeletePV(int id, ref string[] errors) {
            return base.Channel.DeletePV(id, ref errors);
        }
        
        public MVC3.SLProductVariation.ProductVariationInfo[] ReadAllPV(ref string[] errors) {
            return base.Channel.ReadAllPV(ref errors);
        }
        
        public MVC3.SLProductVariation.ProductVariationInfo[] ReadAllPVCondition(char status, ref string[] errors) {
            return base.Channel.ReadAllPVCondition(status, ref errors);
        }
    }
}
