//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.SLProductCutting {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductColorInfo", Namespace="http://schemas.datacontract.org/2004/07/DomainModel")]
    [System.SerializableAttribute()]
    public partial class ProductColorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_color_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_color_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_color_id {
            get {
                return this.product_color_idField;
            }
            set {
                if ((this.product_color_idField.Equals(value) != true)) {
                    this.product_color_idField = value;
                    this.RaisePropertyChanged("product_color_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_color_name {
            get {
                return this.product_color_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_color_nameField, value) != true)) {
                    this.product_color_nameField = value;
                    this.RaisePropertyChanged("product_color_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLProductCutting.ISLProductColor")]
    public interface ISLProductColor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductColor/ReadProductColor", ReplyAction="http://tempuri.org/ISLProductColor/ReadProductColorResponse")]
        MVC3.SLProductCutting.ProductColorInfo ReadProductColor(int id, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductColor/CreateProductColor", ReplyAction="http://tempuri.org/ISLProductColor/CreateProductColorResponse")]
        int CreateProductColor(string name, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductColor/UpdateProductColor", ReplyAction="http://tempuri.org/ISLProductColor/UpdateProductColorResponse")]
        int UpdateProductColor(int id, string name, ref string[] errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLProductColor/ReadAllProductColor", ReplyAction="http://tempuri.org/ISLProductColor/ReadAllProductColorResponse")]
        MVC3.SLProductCutting.ProductColorInfo[] ReadAllProductColor(ref string[] errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLProductColorChannel : MVC3.SLProductCutting.ISLProductColor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLProductColorClient : System.ServiceModel.ClientBase<MVC3.SLProductCutting.ISLProductColor>, MVC3.SLProductCutting.ISLProductColor {
        
        public SLProductColorClient() {
        }
        
        public SLProductColorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLProductColorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLProductColorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLProductColorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC3.SLProductCutting.ProductColorInfo ReadProductColor(int id, ref string[] errors) {
            return base.Channel.ReadProductColor(id, ref errors);
        }
        
        public int CreateProductColor(string name, ref string[] errors) {
            return base.Channel.CreateProductColor(name, ref errors);
        }
        
        public int UpdateProductColor(int id, string name, ref string[] errors) {
            return base.Channel.UpdateProductColor(id, name, ref errors);
        }
        
        public MVC3.SLProductCutting.ProductColorInfo[] ReadAllProductColor(ref string[] errors) {
            return base.Channel.ReadAllProductColor(ref errors);
        }
    }
}
